import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  containerstyle: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 20,
  },
  text: {
    fontFamily: 'Poppins-Bold',
    color: '#2E1E5C',
    fontSize: 14,
  },
  textlight: {
    fontFamily: 'Poppins-Regular',
    color: '#C4C4C4',
    fontSize: 12,
    textAlign: 'center',
  },
  icon: {
    width: 35,
    height: 35,
    borderRadius: 100,
    backgroundColor: '#08C0CA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headercontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 40,
    justifyContent: 'space-between',
  },
  card1: {
    width: 90,
    height: 90,
    backgroundColor: '#fff',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    marginBottom: 10,
    elevation: 5,
    position: 'relative',
  },
  card2: {
    height: 130,
    backgroundColor: '#fff',
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    marginBottom: 10,
    elevation: 3,
    position: 'relative',
    justifyContent: 'center',
  },
  pickscontainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
    alignItems: 'center',
  },
  cardcontainer: {marginVertical: 15, marginTop: 5, marginHorizontal: 3},
});
